modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="https://github.com/Alex-the-666/ice-and-fire/issues" #optional
license="GNU LESSER GENERAL PUBLIC LICENSE"
[[mods]] #mandatory
modId="iceandfire" #mandatory
version="2.1.9-1.16.5" #mandatory
displayName="Ice and Fire" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons" #optional
authors="Alexthe666" #optional
description='''Dragons and other mythological creatures in minecraft.'''
[[dependencies.iceandfire]] #optional
    # the modid of the dependency
    modId="citadel" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[1.8.1,1.8.99]" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="AFTER"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"